apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: michaeljohn32-michaeljohn32-poi-map-app-dev
  annotations:
    argocd/app-name: michaeljohn32-michaeljohn32-poi-map-app-dev
    backstage.io/kubernetes-id: michaeljohn32-michaeljohn32-poi-map-app-dev
    backstage.io/kubernetes-namespace: michaeljohn32
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=michaeljohn32-michaeljohn32-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/michaeljohn32-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/michaeljohn32/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/michaeljohn32/deployments/michaeljohn32-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/michaeljohn32-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://michaeljohn32-poi-map-app-michaeljohn32.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/michaeljohn32"
  system: workshop-system-michaeljohn32
  consumesApis:
    - gateway-api-michaeljohn32
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-michaeljohn32
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/michaeljohn32"
